INSERT INTO Criteria
	(decision_id, criterion_text, criterion_importance)
VALUES 
  (1, "Walkability", 2),
  (1, "Square Footage", 5),
  (1, "Pool", 4),
  (1, "Yard", 5),
  (2, "Affordability of travel", 3),
  (2, "Ability to see friends", 4),
  (2, "Warm climate for a break from the cold", 1),
  (2, "Interesting culture", 2),
  (3, "Relevance to future", 3),
  (3, "Earning potential", 5),
  (3, "Job security", 4),
  (3, "Stimulating subject", 3),
  (4, "Friedly landlord", 3),
  (4, "spaciousness", 4),
  (4, "neighborhood", 5),
  (4, "affordable rent", 4),
  (5, "Low cost to students", 4),
  (5, "Applicability in classroom", 5),
  (5, "Cultural relevance", 3),
  (5, "Online companion website", 5),
  (6, "Beginner friendliness", 2),
  (6, "Monthly cost", 2),
  (6, "Quality of teachers", 4),
  (6, "Proximity to home", 3),
  (7, "Easy to cook", 1),
  (7, "Adventurous meal", 3),
  (7, "Impressive", 5),
  (7, "Unique", 5),
  (8, "Versatility - can play many different styles and sound good", 5),
  (8, "Durability", 3),
  (8, "Customizability", 2),
  (8, "Portability to gigs", 1),
  (9, "Begginner friendly", 2),
  (9, "Low monthly cost", 3),
  (9, "Good community", 4),
  (9, "Offers hot yoga", 2),
  (10, "Is a person who knows my work well", 1),
  (10, "Is a person who is reputable", 3),
  (10, "Is a professor whose courses I did well in", 4),
  (10, "Is willing to work with me in person", 5),
  (11, "Earning potential", 1),
  (11, "Future proofness", 5),
  (11, "Opportunity for advancement", 4),
  (11, "Lifestyle flexibility", 3),
  (12, "Political relevance to the future", 2),
  (12, "Easy opportunities to learn and practice", 3),
  (12, "Spoken by a large population", 4),
  (12, "Demand by future employers", 5),
  (13, "Financial Transparency", 2),
  (13, "Past track record", 3),
  (13, "Directly helps those in need", 5),
  (13, "Credibility", 4);