INSERT INTO Options
	(decision_id, option_text)
VALUES 
  (1, "The blue house"),
  (1, "the green house"),
  (1, "the brown house"),
  (2, "Costa rica"),
  (2, "Friends house in London"),
  (2, "San Macos, TX"),
  (3, "Computer science"),
  (3, "Biology"),
  (3, "History"),
  (4, "The blue apartment"),
  (4, "The green apartment"),
  (4, "the brown apartment"),
  (5, "Arabic for Dummies"),
  (5, "Integrated Arabic"),
  (5, "Practical Arabic for Beginners"),
  (6, "The Austin Zen Center"),
  (6, "The Houston Zen Center"),
  (6, "Tibetan Buddhism and Meditation Center"),
  (7, "Fettuccine Alfredo"),
  (7, "Chicken Tikka Masala"),
  (7, "Homemade Pizza"),
  (8, "Martin Acoustic D18"),
  (8, "Fender Strat Texas Blues Edition"),
  (8, "Ibanez Hybrid"),
  (9, "Yoga One"),
  (9, "Just Breathe Yoga"),
  (9, "The Yoga Learning Co-op"),
  (10, "Professor X"),
  (10, "Professor Y"),
  (10, "Professor Z"),
  (11, "Web Developer"),
  (11, "Accountant"),
  (11, "Plumber"),
  (12, "Arabic"),
  (12, "Chinese"),
  (12, "Spanish"),
  (13, "Animal Rescue Charity"),
  (13, "Cancer Research Charity"),
  (13, "Houston Direct Action Relief Fund");


